### PR TITLE
[Add] length of longest palindromic substring (dp)

### PR DESCRIPTION
**Pull request by iamsank7**
Added the cpp code for the length of longest palindromic substring using dynamic programming.

### CODE REVIEW

**Comment by Syzygianinfern0** [comment]
Nice bro :100:

**Comment by Syzygianinfern0** [comment]
Teach me also pls :bow:

**Review by barath99 — APPROVED** [review]

**Comment by Syzygianinfern0** [comment]
PR for me?

**Comment by Syzygianinfern0** [comment]
Even I want sir

**Comment by Syzygianinfern0** [comment]
Pee arr

**Pull request merged**
